theme: jekyll-theme-slate
title: Supplementary Material---Capturing the Effect of Mass Ratio in Three-Dimensional Hydrodynamical Local Simulations of the Common Envelope Inspiral Phase of Binary Stars 
show_downloads: true
